// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBavczQKP-XW8C9p6Ge_S4XcnwwSCLNR7o',
    appId: '1:87674806781:web:d9511a8cafa7735a46b994',
    messagingSenderId: '87674806781',
    projectId: 'socialmediaproject-a11c2',
    authDomain: 'socialmediaproject-a11c2.firebaseapp.com',
    databaseURL: 'https://socialmediaproject-a11c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmediaproject-a11c2.appspot.com',
    measurementId: 'G-4LPHK23RVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ArrBiM9R2E8uqgRyrgY71Zg_CVtQ_O0',
    appId: '1:87674806781:android:292c53fa6d2f50ee46b994',
    messagingSenderId: '87674806781',
    projectId: 'socialmediaproject-a11c2',
    databaseURL: 'https://socialmediaproject-a11c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmediaproject-a11c2.appspot.com',
  );
}
